edition = "2024"
style_edition = "2024"
max_width = 100
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
unstable_features = true
group_imports = "StdExternalCrate"
use_small_heuristics = "Max"
fn_single_line = false
normalize_comments = true
wrap_comments = true
comment_width = 80
overflow_delimited_expr = true
reorder_impl_items = true
