[package]
name = "rmpc"
version = "0.11.0"
description = "A beautiful and configurable TUI client for MPD"
readme = "README.md"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
rmpc-mpd = { path = "../rmpc-mpd" }
rmpc-shared = { path = "../rmpc-shared" }
ansi_colours = { workspace = true }
anyhow = { workspace = true }
base64 = { workspace = true }
bitflags = { workspace = true }
bon = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
color_quant = { workspace = true }
crossbeam = { workspace = true }
crossterm = { workspace = true }
derive_more = { workspace = true }
dialoguer = { workspace = true }
either = { workspace = true }
enum-map = { workspace = true }
flate2 = { workspace = true }
flexi_logger = { workspace = true }
image = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
notify-debouncer-full = { workspace = true }
parking_lot = { workspace = true }
ratatui = { workspace = true }
ron = { workspace = true }
rustix = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_path_to_error = { workspace = true }
serde_with = { workspace = true }
serde_yaml_ng = { workspace = true }
strum = { workspace = true }
sysinfo = { workspace = true }
textwrap = { workspace = true }
thiserror = { workspace = true }
unicase = { workspace = true }
unicode-segmentation = { workspace = true }
unicode-width = { workspace = true }
url = { workspace = true }
walkdir = { workspace = true }
which = { workspace = true }
winnow = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
test-case = { workspace = true }
rmpc-shared = { path = "../rmpc-shared", features = ["test-impl"] }

[build-dependencies]
rmpc-mpd = { path = "../rmpc-mpd" }
clap = { workspace = true }
strum = { workspace = true }
serde = { workspace = true }
clap_complete = { workspace = true }
clap_mangen = { workspace = true }
vergen-gitcl = { workspace = true }
