name: Test and Validate

on: [pull_request, workflow_dispatch]

jobs:
  test:
    name: Cargo test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Cargo test
      run: |
        cargo test
        cargo test --release
  format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Format check
      run: |
        cargo fmt --check
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run clippy
      run: |
        cargo clippy -- -D warnings
        cargo clippy --release -- -D warnings
  build:
    name: Build check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build check
      run: |
        cargo build
        cargo build --release
