name: Test and Validate

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        toolchain: [stable, nightly]
        profile: [dev, release]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin

    name: Build & Test (${{ matrix.target }}, ${{ matrix.toolchain }}, ${{ matrix.profile }})
    runs-on: ${{ matrix.os }}

    env:
      RA_TARGET: ${{ matrix.target }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.target }}
          profile: minimal
          override: true

      - name: Install Rust library source
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.target }}
          profile: minimal
          override: true
          components: rust-src

      - name: Build
        run: cargo build --verbose --target ${{ matrix.target }} --profile ${{ matrix.profile }}

      - name: Run tests
        run: cargo test --verbose --target ${{ matrix.target }} --profile ${{ matrix.profile }}

  lint:
    name: Formatter

    needs: build-test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        run: |
          rustup update nightly
          rustup default nightly
          rustup component add rustfmt
          rustup component add clippy

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Check code for possible improvements
        run: cargo clippy -- -D warnings
