name: Run Tests

on:
  push:
    branches: [ testing/flaky-tests ]
  workflow_dispatch:

jobs:
  test:
    name: Test Debug Mode
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Cargo test
      run: |
        cargo test
  test-release:
    name: Test Release Mode
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Cargo test
      run: |
        cargo test --release
